### ISSUE TITLE
Incorrect references in main.scss

### ISSUE THREAD

**Issue by opattison** [jeremydouglas/platypus#2]
These two references made gulp fail to build the CSS properly, but these should fix it.

https://github.com/jeremydouglas/platypus/blob/cc7208b551c5ad287c41a30cd82ceb6c81cc9623/src/sass/main.scss#L19

Should be `@import "../../node_modules/sanitize.css/lib/sanitize.scss";` (at least in the latest version of sanitize.scss, there is a `lib` directory where the SCSS file lives). The path can be updated, but is there a more robust way of handling this or similar files imported from `node_modules`? Maybe by locking to only minor releases for SCSS dependencies in the `package.json`? 

https://github.com/jeremydouglas/platypus/blob/cc7208b551c5ad287c41a30cd82ceb6c81cc9623/src/sass/main.scss#L57-L60

SCSS directory is named `settings` rather than `setting`.

**Comment by jeremydouglas** [comment]
Thanks Oliver! Got it.
